version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: devseconnect
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: markus.buergi1986@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - backend

  postgres-exporter:
    image: wrouesnel/postgres_exporter:latest
    environment:
      DATA_SOURCE_NAME: "postgresql://admin:admin@postgres:5432/devseconnect?sslmode=disable"
    depends_on:
      - postgres
    ports:
      - "9187:9187"
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend

  redis-exporter:
    image: oliver006/redis_exporter:latest
    command: --redis.addr=redis:6379
    depends_on:
      - redis
    ports:
      - "9121:9121"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ management console
    environment:
      RABBITMQ_DEFAULT_USER: devseconnect
      RABBITMQ_DEFAULT_PASS: admin1234
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - backend

  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter:latest
    environment:
      RABBIT_URL: http://devseconnect:admin1234@rabbitmq:15672
    depends_on:
      - rabbitmq
    ports:
      - "9419:9419"
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-config:/etc/nginx
    depends_on:
      - web
      - rabbitmq
      - redis
      - postgres
    networks:
      - backend

  web:
    image: golang:latest
    container_name: golang_web_server
    ports:
      - "8080:8080"
    volumes:
      - golang-data:/app
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - backend
      - frontend

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - backend

volumes:
  postgres-data:
  redis-data:
  nginx-config:
  rabbitmq-data:
  golang-data:
  grafana-data:
  prometheus.yml:
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
