apiVersion: apps/v1
kind: Deployment
metadata:
  name: devseconnect-web-server
  labels:
    app: devseconnect-web-server
    version: "0.0.1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devseconnect-web-server
      version: "0.0.1"
  template:
    metadata:
      labels:
        app: devseconnect-web-server
        version: "0.0.1"
    spec:
      containers:
        - name: devseconnect-web-server
          image: buergi1986/devseconnect-web_server:update
          imagePullPolicy: Always
          command: ["/bin/sh", "-c", "sleep infinity"]
          ports:
            - containerPort: 1323
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: devseconnect-config
                  key: PORT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: devseconnect-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: devseconnect-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devseconnect-secret
                  key: DB-PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: devseconnect-config
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: devseconnect-config
                  key: DB_PORT
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: devseconnect-config
                  key: REDIS_URL
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devseconnect-secret
                  key: REDIS-PASSWORD
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: devseconnect-config
                  key: RABBITMQ_URL
            - name: RABBIT_URL
              valueFrom:
                configMapKeyRef:
                  name: devseconnect-config
                  key: RABBIT_URL
            - name: RABBIT_USER
              valueFrom:
                configMapKeyRef:
                  name: devseconnect-config
                  key: RABBIT_USER
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devseconnect-secret
                  key: RABBITMQ-PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: devseconnect-secret
                  key: JWT-SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: devseconnect-web-server-service
spec:
  selector:
    app: devseconnect-web-server
  ports:
    - protocol: TCP
      port: 1323
      targetPort: 1323
  type: ClusterIP # Using ClusterIP, Traefik will handle load balancing and routing to the pods
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golang-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /register
            pathType: Prefix
            backend:
              service:
                name: devseconnect-web-server
                port:
                  number: 1323
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: devseconnect-web-server
                port:
                  number: 1323
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: devseconnect-web-server
                port:
                  number: 1323
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: devseconnect-web-server
                port:
                  number: 1323
          - path: /posts
            pathType: Prefix
            backend:
              service:
                name: devseconnect-web-server
                port:
                  number: 1323
          - path: /post
            pathType: Prefix
            backend:
              service:
                name: devseconnect-web-server
                port:
                  number: 1323
          - path: /comments
            pathType: Prefix
            backend:
              service:
                name: devseconnect-web-server
                port:
                  number: 1323
          - path: /comment
            pathType: Prefix
            backend:
              service:
                name: devseconnect-web-server
                port:
                  number: 1323
          - path: /tags
            pathType: Prefix
            backend:
              service:
                name: devseconnect-web-server
                port:
                  number: 1323
          - path: /tag
            pathType: Prefix
            backend:
              service:
                name: devseconnect-web-server
                port:
                  number: 1323
