apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: database
  labels:
    app: postgres
    app.kubernetes.io/instance: devseconnect
data:
  POSTGRES_DB: devseconnect
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin1234
